version: '3'
services:
  web:
    image: mysql:8.3.0
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root